### ISSUE TITLE
小白询问mac文件的安装

### ISSUE THREAD

**Issue by yangocean-sudo** [llychao/m3u8-downloader#13]
你好，我下载了linux版本，但不知道用什么文件打开m3u8-linux-amd64，我需要下载go语言吗？谢谢！

**Comment by llychao** [comment]
二进制文件可以直接运行------------------ 原始邮件 ------------------发件人: yangocean-sudo  ***@***.***>发送时间: 2021年7月31日 20:56收件人: llychao/m3u8-downloader ***@***.***>抄送: Subscribed ***@***.***>主题: 回复：[llychao/m3u8-downloader] 小白询问mac文件的安装 (#13)
你好，我下载了linux版本，但不知道用什么文件打开m3u8-linux-amd64，我需要下载go语言吗？谢谢！

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/llychao/m3u8-downloader/issues/13",
"url": "https://github.com/llychao/m3u8-downloader/issues/13",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
