### ISSUE TITLE
支持配置解密密钥吗？

### ISSUE THREAD

**Issue by ttbadr** [llychao/m3u8-downloader#25]
如题

**Comment by llychao** [comment]
可以的。等新版本我加一下哦------------------ 原始邮件 ------------------发件人: toby  ***@***.***>发送时间: 2022年1月21日 10:10收件人: llychao/m3u8-downloader ***@***.***>抄送: Subscribed ***@***.***>主题: Re: [llychao/m3u8-downloader] 支持配置解密密钥吗？ (Issue #25)
Closed #25.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/llychao/m3u8-downloader/issues/25#event-5929157344",
"url": "https://github.com/llychao/m3u8-downloader/issues/25#event-5929157344",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kkdxz** [comment]
同样需求
