### ISSUE TITLE
2个问题

### ISSUE THREAD

**Issue by vjsdhyygy** [llychao/m3u8-downloader#3]
1 不能下载嵌套的M3U8 ，如
`https://mudan.iii-kuyunzy.com/20191215/5702_46b0f018/index.m3u8`
使用 curl 查看后
````
curl https://mudan.iii-kuyunzy.com/20191215/5702_46b0f018/index.m3u8
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=800000,RESOLUTION=1080x608
1000k/hls/index.m3u8
````
得到真实地址
 `https://mudan.iii-kuyunzy.com/20191215/5702_46b0f018/1000k/hls/index.m3u8`
可下载

2 不能自定义下载文件名，恳请修改

**Comment by vjsdhyygy** [comment]
好吧，追加第三个问题，合并后会出现一些未知的视频的合并错误，常常有视频会出现莫名其怪的卡顿，跳跃

**Comment by llychao** [comment]
> 1 不能下载嵌套的M3U8 ，如
> `https://mudan.iii-kuyunzy.com/20191215/5702_46b0f018/index.m3u8`
> 使用 curl 查看后
> 
> ```
> curl https://mudan.iii-kuyunzy.com/20191215/5702_46b0f018/index.m3u8
> #EXTM3U
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=800000,RESOLUTION=1080x608
> 1000k/hls/index.m3u8
> ```
> 
> 得到真实地址
> `https://mudan.iii-kuyunzy.com/20191215/5702_46b0f018/1000k/hls/index.m3u8`
> 可下载
> 
> 2 不能自定义下载文件名，恳请修改



1.嵌套地址的暂不考虑支持
2.自定义下载名字 ：加上 -o="自定义名字"
3.合并的卡顿：我也遇到过此问题，目前怀疑有可能是视频资源问题。

**Comment by Kiritomo** [comment]
借楼提个建议，加入自定义请求头，有些密钥需要cookie才能获取

**Comment by llychao** [comment]
收到------------------ 原始邮件 ------------------发件人: 香芋奶茶  <notifications@github.com>发送时间: 2021年3月3日 12:02收件人: llychao/m3u8-downloader <m3u8-downloader@noreply.github.com>抄送: 萌萌站起来 <lychao_vip@163.com>, Comment <comment@noreply.github.com>主题: 回复：[llychao/m3u8-downloader] 2个问题 (#3)
借楼提个建议，加入自定义请求头，有些密钥需要cookie才能获取

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/llychao/m3u8-downloader/issues/3#issuecomment-789410568",
"url": "https://github.com/llychao/m3u8-downloader/issues/3#issuecomment-789410568",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Junyi-99** [comment]
@llychao 合并的卡顿和跳跃，是一个 BUG，具体描述在 #16，解决方案已经提交 Pull Request #17
