### ISSUE TITLE
00007.tspanic: open /dev/null: too many open files

### ISSUE THREAD

**Issue by neohob** [llychao/m3u8-downloader#52]
不加ht=apiv2就报错：00007.tspanic: open /dev/null: too many open files
加了ht=apiv2可以合并成mp4，但是不能播放，ffmpeg的结果是： moov atom not found  123.mp4: Invalid data found when processing input
用了apiv2参数以后好像不显示读取到的key，是不是没有使用key导致合并后的mp4不能用呢

**Comment by neohob** [comment]
key是一串base64的码，解开看到其中包含：m3u8文件请求失败！ +其字符

**Comment by neohob** [comment]
研究了一番，需要鉴权

**Comment by llychao** [comment]
换个通用的播放器。这个不是标准的mp4格式。不过，手机都可以看------------------ Original ------------------From: neohob  ***@***.***>Date: Tue,Aug 16,2022 4:52 PMTo: llychao/m3u8-downloader ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [llychao/m3u8-downloader] 00007.tspanic: open /dev/null: too manyopen files (Issue #52)
不加ht=apiv2就报错：00007.tspanic: open /dev/null: too many open files
加了ht=apiv2可以合并成mp4，但是不能播放，ffmpeg的结果是： moov atom not found  123.mp4: Invalid data found when processing input

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/llychao/m3u8-downloader/issues/52",
"url": "https://github.com/llychao/m3u8-downloader/issues/52",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by neohob** [comment]
key需要解密，不是播放器问题，解决了
