### ISSUE TITLE
请问支持m1吗？

### ISSUE THREAD

**Issue by Dopa4** [llychao/m3u8-downloader#53]
请问支持m1吗

**Comment by llychao** [comment]
支持，我的就是m1------------------ 原始邮件 ------------------发件人: 3.3  ***@***.***>发送时间: 2022年9月7日 18:44收件人: llychao/m3u8-downloader ***@***.***>抄送: Subscribed ***@***.***>主题: Re: [llychao/m3u8-downloader] 请问支持m1吗？ (Issue #53)
请问支持m1吗

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/llychao/m3u8-downloader/issues/53",
"url": "https://github.com/llychao/m3u8-downloader/issues/53",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
